# GitHub loyihangiz uchun homiylik platformalari

github: [Asilbek2706] # GitHub Sponsors foydalanuvchi nomingiz
patreon: Asilbek2706             # Patreon foydalanuvchi nomingiz
open_collective: Asilbek2706     # Open Collective foydalanuvchi nomingiz
ko_fi: Asilbek2706               # Ko-fi foydalanuvchi nomingiz
liberapay: Asilbek2706           # Liberapay foydalanuvchi nomingiz
issuehunt: Asilbek2706           # IssueHunt foydalanuvchi nomingiz
polar: Asilbek2706               # Polar foydalanuvchi nomingiz
buy_me_a_coffee: Asilbek2706     # Buy Me a Coffee foydalanuvchi nomingiz
thanks_dev: Asilbek2706          # thanks.dev foydalanuvchi nomingiz
custom: ['https://t.me/as1lbek_2706'] # Boshqa shaxsiy homiylik havolalari
